# Generated by Django 6.0.6 on 2026-06-08 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='core.school')),
            ],
            options={
                'db_table': 'forms',
                'ordering': ['order', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Homeroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homerooms', to='scheduling.form')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homerooms', to='core.school')),
            ],
            options={
                'db_table': 'homerooms',
                'ordering': ['form', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
