# Generated by Django 6.0.6 on 2026-06-22 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enrolments',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'forms',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormTermRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveIntegerField()),
                ('exam_label', models.CharField(default='Final Exam', max_length=100)),
                ('exam_replaces_final', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'form_term_rules',
            },
        ),
        migrations.CreateModel(
            name='Homeroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'homerooms',
                'ordering': ['form', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NonSchoolDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('holiday', 'Public Holiday'), ('impromptu', 'Impromptu Closure'), ('event', 'School Event')], max_length=20)),
            ],
            options={
                'db_table': 'non_school_days',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveIntegerField()),
                ('room', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['academic_year', 'term_number', 'course'],
            },
        ),
        migrations.CreateModel(
            name='TermConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('has_final_exam', models.BooleanField(default=True)),
                ('coursework_weight', models.PositiveIntegerField(default=60)),
                ('exam_weight', models.PositiveIntegerField(default=40)),
            ],
            options={
                'db_table': 'term_configs',
                'ordering': ['term_number'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['form', 'academic_year', 'term_number'],
            },
        ),
        migrations.CreateModel(
            name='TimetablePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_break', models.BooleanField(default=False, help_text='Recess, lunch, assembly — no class scheduled.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('cycle', 'Rotating day cycle (Day 1 … Day N)'), ('weekday', 'Regular weekly (Mon – Fri)')], default='weekday', max_length=10)),
                ('cycle_length', models.PositiveSmallIntegerField(default=6)),
                ('anchor_date', models.DateField(blank=True, help_text='The first school day on/after this date is Day 1. Usually the first day of the academic year.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(help_text='Cycle mode: 1..N = Day 1..Day N. Weekly mode: 1=Mon … 5=Fri.')),
            ],
            options={
                'ordering': ['day_number', 'period__order'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.school')),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('short_description', models.CharField(blank=True, max_length=8)),
                ('description', models.TextField(blank=True)),
                ('section_number', models.CharField(blank=True, default='1', max_length=10)),
                ('start_term', models.PositiveIntegerField(blank=True, null=True)),
                ('end_term', models.PositiveIntegerField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=100)),
                ('web_visible', models.BooleanField(default=True)),
                ('instructional_mode', models.CharField(blank=True, choices=[('lecture', 'Lecture'), ('lab', 'Laboratory'), ('online', 'Online'), ('hybrid', 'Hybrid'), ('practical', 'Practical'), ('other', 'Other')], max_length=20)),
                ('faculty', models.CharField(blank=True, max_length=100)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('subject_area', models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('sciences', 'Sciences'), ('languages', 'Languages'), ('social_studies', 'Social Studies'), ('technology', 'Technology'), ('arts', 'Arts'), ('physical_ed', 'Physical Education'), ('other', 'Other')], max_length=30)),
                ('calc_average', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.school')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['sequence', 'name'],
            },
        ),
    ]
