# Generated by Django 6.0.6 on 2026-06-22 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_courses', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_courses', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='students.student'),
        ),
        migrations.AddField(
            model_name='form',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='core.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_masters', to='scheduling.form'),
        ),
        migrations.AddField(
            model_name='formtermrule',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_term_rules', to='scheduling.academicyear'),
        ),
        migrations.AddField(
            model_name='formtermrule',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_rules', to='scheduling.form'),
        ),
        migrations.AddField(
            model_name='homeroom',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homerooms', to='scheduling.form'),
        ),
        migrations.AddField(
            model_name='homeroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homerooms', to='core.school'),
        ),
        migrations.AddField(
            model_name='nonschoolday',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonschoolday',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_school_days', to='core.school'),
        ),
        migrations.AddField(
            model_name='section',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scheduling.academicyear'),
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scheduling.course'),
        ),
        migrations.AddField(
            model_name='section',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scheduling.form'),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.school'),
        ),
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='scheduling.section'),
        ),
        migrations.AddField(
            model_name='termconfig',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_configs', to='scheduling.academicyear'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='scheduling.academicyear'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='scheduling.form'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='core.school'),
        ),
        migrations.AddField(
            model_name='timetableperiod',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_periods', to='core.school'),
        ),
        migrations.AddField(
            model_name='timetablesettings',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_settings', to='core.school'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduling.timetableperiod'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='core.school'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='scheduling.section'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduling.timetable'),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='formtermrule',
            unique_together={('academic_year', 'form', 'term_number')},
        ),
        migrations.AlterUniqueTogether(
            name='homeroom',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='nonschoolday',
            unique_together={('school', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together={('student', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='termconfig',
            unique_together={('academic_year', 'term_number')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('school', 'form', 'academic_year', 'term_number')},
        ),
        migrations.AlterUniqueTogether(
            name='timetableperiod',
            unique_together={('school', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('timetable', 'day_number', 'period', 'section')},
        ),
    ]
