# Generated by Django 6.0.6 on 2026-06-08 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.school')),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.school')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveIntegerField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scheduling.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scheduling.course')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scheduling.form')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.school')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='staff.staff')),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['academic_year', 'term_number', 'course'],
            },
        ),
        migrations.CreateModel(
            name='FormTermRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveIntegerField()),
                ('exam_label', models.CharField(default='Final Exam', max_length=100)),
                ('exam_replaces_final', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_term_rules', to='scheduling.academicyear')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_rules', to='scheduling.form')),
            ],
            options={
                'db_table': 'form_term_rules',
                'unique_together': {('academic_year', 'form', 'term_number')},
            },
        ),
        migrations.CreateModel(
            name='NonSchoolDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('holiday', 'Public Holiday'), ('impromptu', 'Impromptu Closure'), ('event', 'School Event')], max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_school_days', to='core.school')),
            ],
            options={
                'db_table': 'non_school_days',
                'ordering': ['date'],
                'unique_together': {('school', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='students.student')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='scheduling.section')),
            ],
            options={
                'db_table': 'enrolments',
                'unique_together': {('student', 'section')},
            },
        ),
        migrations.CreateModel(
            name='TermConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('has_final_exam', models.BooleanField(default=True)),
                ('coursework_weight', models.PositiveIntegerField(default=60)),
                ('exam_weight', models.PositiveIntegerField(default=40)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_configs', to='scheduling.academicyear')),
            ],
            options={
                'db_table': 'term_configs',
                'ordering': ['term_number'],
                'unique_together': {('academic_year', 'term_number')},
            },
        ),
    ]
