# Generated by Django 6.0.6 on 2026-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
