# Generated by Django 6.0.6 on 2026-06-09 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_academicyear_course_section_formtermrule_and_more'),
        ('staff', '0002_remove_staff_email_remove_staff_phone_staff_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['sequence', 'name']},
        ),
        migrations.AddField(
            model_name='course',
            name='calc_average',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end_term',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_masters', to='scheduling.form'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructional_mode',
            field=models.CharField(blank=True, choices=[('lecture', 'Lecture'), ('lab', 'Laboratory'), ('online', 'Online'), ('hybrid', 'Hybrid'), ('practical', 'Practical'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='section_number',
            field=models.CharField(blank=True, default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='sequence',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='course',
            name='start_term',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_area',
            field=models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('sciences', 'Sciences'), ('languages', 'Languages'), ('social_studies', 'Social Studies'), ('technology', 'Technology'), ('arts', 'Arts'), ('physical_ed', 'Physical Education'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_courses', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_courses', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='course',
            name='web_visible',
            field=models.BooleanField(default=True),
        ),
    ]
