# Generated by Django 6.0.6 on 2026-07-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_termconfig_end_date_termconfig_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, choices=[('Mathematics', 'Mathematics'), ('English', 'English / Language Arts'), ('Natural Sciences', 'Natural Sciences'), ('Social Studies', 'Social Studies'), ('Modern Languages', 'Modern Languages'), ('Information Technology', 'Information Technology'), ('Business Studies', 'Business Studies'), ('Physical Education', 'Physical Education'), ('Visual & Performing Arts', 'Visual & Performing Arts'), ('Technical', 'Technical'), ('Religious Education', 'Religious Education'), ('Building & Tech Draw', 'Building & Technical Drawing'), ('Geography', 'Geography'), ('History', 'History'), ('Agriculture', 'Agriculture')], help_text='Department that owns this course. Heads of this department can view its grades.', max_length=100),
        ),
    ]
