# Generated by Django 6.0.6 on 2026-08-04 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_course_department'),
        ('students', '0003_add_year_placement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('continuing', 'Continuing'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated'), ('not_graduated', 'Not Graduated')], default='continuing', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='scheduling.academicyear')),
                ('homeroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_placements', to='scheduling.homeroom')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_placements_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_placements', to='students.student')),
            ],
            options={
                'db_table': 'year_placements',
                'ordering': ['-academic_year__name', 'student'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
