# Generated by Django 6.0.6 on 2026-08-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_add_year_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearplacement',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_placements', to='scheduling.form'),
        ),
    ]
