# Generated by Django 6.0.6 on 2026-06-22 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guardians", to="core.school")),
            ],
            options={
                "db_table": "guardians",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(blank=True, max_length=7)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="houses", to="core.school")),
            ],
            options={
                "db_table": "houses",
                "ordering": ["name"],
                "unique_together": {("school", "name")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("student_id", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("gender", models.CharField(blank=True, choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=1)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                (
                    "religion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("roman_catholic", "Roman Catholic"),
                            ("anglican", "Anglican"),
                            ("seventh_day", "Seventh Day Adventist"),
                            ("pentecostal", "Pentecostal"),
                            ("methodist", "Methodist"),
                            ("baptist", "Baptist"),
                            ("jehovah", "Jehovah's Witness"),
                            ("muslim", "Muslim"),
                            ("hindu", "Hindu"),
                            ("other", "Other"),
                            ("none", "None"),
                        ],
                        max_length=30,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("parish", models.CharField(blank=True, max_length=100)),
                ("community", models.CharField(blank=True, max_length=100)),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("previous_school", models.CharField(blank=True, max_length=200)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="students/photos/")),
                ("emis_id", models.CharField(blank=True, max_length=50)),
                ("csec_candidate_no", models.CharField(blank=True, max_length=50)),
                ("cohort_grade", models.CharField(blank=True, max_length=20)),
                ("cohort_year", models.CharField(blank=True, max_length=10)),
                ("repeated", models.CharField(blank=True, max_length=100)),
                ("gsna_year", models.CharField(blank=True, max_length=10)),
                ("gsna_award", models.CharField(blank=True, max_length=50)),
                (
                    "gsna_english",
                    models.CharField(
                        blank=True,
                        choices=[("", "—"), ("1", "Grade 1"), ("2", "Grade 2"), ("3", "Grade 3"), ("4", "Grade 4"), ("5", "Grade 5"), ("6", "Grade 6")],
                        max_length=1,
                    ),
                ),
                (
                    "gsna_mathematics",
                    models.CharField(
                        blank=True,
                        choices=[("", "—"), ("1", "Grade 1"), ("2", "Grade 2"), ("3", "Grade 3"), ("4", "Grade 4"), ("5", "Grade 5"), ("6", "Grade 6")],
                        max_length=1,
                    ),
                ),
                (
                    "gsna_science",
                    models.CharField(
                        blank=True,
                        choices=[("", "—"), ("1", "Grade 1"), ("2", "Grade 2"), ("3", "Grade 3"), ("4", "Grade 4"), ("5", "Grade 5"), ("6", "Grade 6")],
                        max_length=1,
                    ),
                ),
                (
                    "gsna_social_studies",
                    models.CharField(
                        blank=True,
                        choices=[("", "—"), ("1", "Grade 1"), ("2", "Grade 2"), ("3", "Grade 3"), ("4", "Grade 4"), ("5", "Grade 5"), ("6", "Grade 6")],
                        max_length=1,
                    ),
                ),
                ("grad_date", models.DateField(blank=True, null=True)),
                ("sponsor", models.CharField(blank=True, max_length=200)),
                ("father_name", models.CharField(blank=True, max_length=200)),
                ("mother_name", models.CharField(blank=True, max_length=200)),
                ("emergency_contact_name", models.CharField(blank=True, max_length=200)),
                ("emergency_relation", models.CharField(blank=True, max_length=100)),
                ("emergency_phone_1", models.CharField(blank=True, max_length=30)),
                ("emergency_phone_2", models.CharField(blank=True, max_length=30)),
                ("emergency_work_phone", models.CharField(blank=True, max_length=30)),
                ("emergency_workplace", models.CharField(blank=True, max_length=200)),
                ("doctor_name", models.CharField(blank=True, max_length=200)),
                ("doctor_phone", models.CharField(blank=True, max_length=30)),
                ("restrict_contact_1", models.CharField(blank=True, max_length=200)),
                ("restrict_contact_2", models.CharField(blank=True, max_length=200)),
                (
                    "lives_with",
                    models.CharField(
                        blank=True,
                        choices=[("both_parents", "Both Parents"), ("mother", "Mother"), ("father", "Father"), ("guardian", "Guardian"), ("other", "Other")],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("form", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="students", to="scheduling.form")),
                (
                    "homeroom",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="students", to="scheduling.homeroom"),
                ),
                ("house", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="students", to="students.house")),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="students", to="core.school")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_profile", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "ordering": ["last_name", "first_name"],
                "unique_together": {("school", "student_id")},
            },
        ),
        migrations.CreateModel(
            name="StudentStatusLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("withdrawn", "Withdrawn"),
                            ("suspended", "Suspended"),
                            ("graduated", "Graduated"),
                            ("transferred", "Transferred"),
                            ("on_leave", "On Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("change_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="status_changes", to=settings.AUTH_USER_MODEL),
                ),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_logs", to="students.student")),
            ],
            options={
                "db_table": "student_status_logs",
                "ordering": ["-change_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("sibling", "Sibling"),
                            ("uncle", "Uncle"),
                            ("aunt", "Aunt"),
                            ("grandparent", "Grandparent"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("can_pickup", models.BooleanField(default=True)),
                ("guardian", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="students", to="students.guardian")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guardians", to="students.student")),
            ],
            options={
                "db_table": "student_guardians",
                "unique_together": {("student", "guardian")},
            },
        ),
    ]
