# Generated by Django 6.0.6 on 2026-06-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_city_student_cohort_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatuslog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentstatuslog',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
