# Generated by Django 6.0.6 on 2026-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatuslog',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('not_graduated', 'Not Graduated'), ('transferred', 'Transferred'), ('on_leave', 'On Leave')], max_length=20),
        ),
    ]
