# Generated by Django 6.0.6 on 2026-08-04 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_add_year_placement'),
        ('students', '0003_add_year_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatuslog',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_status_logs', to='scheduling.academicyear'),
        ),
    ]
