# Generated by Django 6.0.6 on 2026-06-22 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_number", models.CharField(max_length=50, unique=True)),
                (
                    "salutation",
                    models.CharField(
                        blank=True, choices=[("Mr", "Mr"), ("Mrs", "Mrs"), ("Ms", "Ms"), ("Dr", "Dr"), ("Rev", "Rev"), ("Hon", "Hon")], max_length=10
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("gender", models.CharField(blank=True, choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=1)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("social_security_no", models.CharField(blank=True, max_length=50)),
                ("house", models.CharField(blank=True, max_length=100)),
                ("emis_id", models.CharField(blank=True, max_length=50)),
                ("phone_1", models.CharField(blank=True, max_length=30)),
                ("phone_2", models.CharField(blank=True, max_length=30)),
                ("phone_3", models.CharField(blank=True, max_length=30)),
                ("email_work", models.EmailField(blank=True, max_length=254)),
                ("email_personal", models.EmailField(blank=True, max_length=254)),
                ("email_emis", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("parish", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("role_title", models.CharField(blank=True, max_length=100)),
                ("subject_specialisation", models.CharField(blank=True, max_length=100)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("does_attendance", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("emergency_contact_name", models.CharField(blank=True, max_length=200)),
                ("emergency_contact_phone", models.CharField(blank=True, max_length=30)),
                (
                    "emergency_contact_relation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spouse", "Spouse"),
                            ("parent", "Parent"),
                            ("sibling", "Sibling"),
                            ("child", "Child"),
                            ("friend", "Friend"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "teacher_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("trained", "Trained Teacher"),
                            ("untrained", "Untrained Teacher"),
                            ("temporary", "Temporary"),
                            ("substitute", "Substitute"),
                            ("administrator", "Administrator"),
                            ("support", "Support Staff"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_started_teaching", models.DateField(blank=True, null=True)),
                ("date_appointed", models.DateField(blank=True, null=True)),
                ("previous_schools", models.TextField(blank=True)),
                (
                    "highest_degree",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("certificate", "Certificate"),
                            ("associate", "Associate Degree"),
                            ("bachelor", "Bachelor's Degree"),
                            ("postgrad", "Post-Graduate Certificate"),
                            ("master", "Master's Degree"),
                            ("doctorate", "Doctorate / PhD"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("degree_specification", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "homeroom",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="staff_members", to="scheduling.homeroom"
                    ),
                ),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="staff", to="core.school")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="staff_profile", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "staff",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
