# Generated by Django 6.0.6 on 2026-07-20 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('scheduling', '0005_termconfig_end_date_termconfig_start_date'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department_2',
            field=models.CharField(blank=True, choices=[('Mathematics', 'Mathematics'), ('English', 'English / Language Arts'), ('Natural Sciences', 'Natural Sciences'), ('Social Studies', 'Social Studies'), ('Modern Languages', 'Modern Languages'), ('Information Technology', 'Information Technology'), ('Business Studies', 'Business Studies'), ('Physical Education', 'Physical Education'), ('Visual & Performing Arts', 'Visual & Performing Arts'), ('Technical', 'Technical'), ('Religious Education', 'Religious Education'), ('Building & Tech Draw', 'Building & Technical Drawing'), ('Geography', 'Geography'), ('History', 'History'), ('Agriculture', 'Agriculture')], max_length=100, verbose_name='Second department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_head_of_department',
            field=models.BooleanField(default=False, verbose_name='Head of Department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, choices=[('Mathematics', 'Mathematics'), ('English', 'English / Language Arts'), ('Natural Sciences', 'Natural Sciences'), ('Social Studies', 'Social Studies'), ('Modern Languages', 'Modern Languages'), ('Information Technology', 'Information Technology'), ('Business Studies', 'Business Studies'), ('Physical Education', 'Physical Education'), ('Visual & Performing Arts', 'Visual & Performing Arts'), ('Technical', 'Technical'), ('Religious Education', 'Religious Education'), ('Building & Tech Draw', 'Building & Technical Drawing'), ('Geography', 'Geography'), ('History', 'History'), ('Agriculture', 'Agriculture')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.CheckConstraint(condition=models.Q(('is_head_of_department', False), models.Q(('department', ''), _negated=True), _connector='OR'), name='hod_requires_department'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.CheckConstraint(condition=models.Q(('department_2', ''), models.Q(('department', ''), _negated=True), _connector='OR'), name='second_department_requires_first'),
        ),
    ]
