# Generated by Django 6.0.6 on 2026-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_appointed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_started_teaching',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='degree_specification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='does_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='email_emis',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='email_personal',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='email_work',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child'), ('friend', 'Friend'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='emis_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='highest_degree',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('certificate', 'Certificate'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('postgrad', 'Post-Graduate Certificate'), ('master', "Master's Degree"), ('doctorate', 'Doctorate / PhD'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='house',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='parish',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='staff',
            name='previous_schools',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Rev', 'Rev'), ('Hon', 'Hon')], max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='social_security_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='teacher_type',
            field=models.CharField(blank=True, choices=[('trained', 'Trained Teacher'), ('untrained', 'Untrained Teacher'), ('temporary', 'Temporary'), ('substitute', 'Substitute'), ('administrator', 'Administrator'), ('support', 'Support Staff'), ('other', 'Other')], max_length=20),
        ),
    ]
