# Generated by Django 6.0.6 on 2026-07-05 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('grades', '0003_reportcard_comment'),
        ('scheduling', '0005_termconfig_end_date_termconfig_start_date'),
        ('students', '0002_studentnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_comments_entered', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_comments', to='core.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_comments', to='scheduling.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_comments', to='students.student')),
            ],
            options={
                'db_table': 'grade_comments',
                'unique_together': {('section', 'student')},
            },
        ),
    ]
