# Generated by Django 6.0.6 on 2026-07-05 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_gradecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcard',
            name='status',
        ),
    ]
