# Generated by Django 6.0.6 on 2026-06-08 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemeritRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('misconduct', 'Misconduct'), ('tardiness', 'Tardiness'), ('uniform', 'Uniform Violation'), ('disrespect', 'Disrespect'), ('dishonesty', 'Dishonesty'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField()),
                ('points', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demerits_awarded', to='staff.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demerit_records', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demerit_records', to='students.student')),
            ],
            options={
                'db_table': 'demerit_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MeritRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('behaviour', 'Behaviour'), ('sports', 'Sports'), ('arts', 'Arts'), ('community', 'Community Service'), ('leadership', 'Leadership'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField()),
                ('points', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merits_awarded', to='staff.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_records', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_records', to='students.student')),
            ],
            options={
                'db_table': 'merit_records',
                'ordering': ['-date'],
            },
        ),
    ]
