# Generated by Django 6.0.6 on 2026-06-22 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('merits', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demeritrecord',
            name='awarded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demerits_awarded', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='demeritrecord',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demerit_records', to='core.school'),
        ),
        migrations.AddField(
            model_name='demeritrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demerit_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='meritrecord',
            name='awarded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merits_awarded', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='meritrecord',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_records', to='core.school'),
        ),
        migrations.AddField(
            model_name='meritrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_records', to='students.student'),
        ),
    ]
