# Generated by Django 6.0.6 on 2026-08-06 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merits', '0002_initial'),
        ('scheduling', '0008_add_form_to_year_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='demeritrecord',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demerit_records', to='scheduling.academicyear'),
        ),
        migrations.AddField(
            model_name='meritrecord',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merit_records', to='scheduling.academicyear'),
        ),
    ]
