# Generated by Django 6.0.6 on 2026-06-09 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('scheduling', '0002_academicyear_course_section_formtermrule_and_more'),
        ('students', '0002_student_city_student_cohort_grade_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='homeroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='scheduling.homeroom'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='scheduling.section'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'homeroom', 'date')},
        ),
    ]
