# Generated by Django 6.0.6 on 2026-08-05 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('scheduling', '0008_add_form_to_year_placement'),
        ('students', '0004_add_academic_year_to_statuslog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='scheduling.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'academic_year', 'date')},
        ),
    ]
